name: Manual PyPI Publish

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    # Use current branch/tag
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build

    - name: Build distribution
      run: python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
